model_name: 'bsds_segmentor'
skip_prep_data: True
dataset_dir: 'D:\backup_project\BSR_bsds500\BSDS500\data'
#Model
skip_training: True
input_size: [512, 512]
in_channels: 3
out_channels: 64
num_classes: 64
features: [64, 128, 256, 512]
bilinear: True
max_len: 65536
d_model: 256
nhead: 8
num_encoder_layers: 6
num_decoder_layers: 6
dim_feedforward: 1024

#Settings
learning_rate: 0.0001
monitor: 'val_loss'
epochs: 50
batch_size: 4
clear_cache: False
limit:
logger_dir: 'lightning_logs'
resume_ckpt: True
