model_name: 'pix2pix_video_segmentor'
train_val_ratio: [0.95, 0.05]
skip_prep_data: False
val_prediction_fstr: 'val_predictions/video_seg/{id}/{annotated_fids}.jpg'
#Model
datasets:
  a2d-video-segmentation:
    pipeline_fn: "a2d_splits_df"
    train_val_ratio: [0.95, 0.05]
    dataset_dir: 'D:/video_datasets'

max_num_objects: 80
skip_training: False
input_size: [320, 768]
# pix2pix settings
patch_size: 256
gen_features: 64
n_gen_enc: 6
disc_features: [64, 128, 256, 512]
out_channels: 80
in_channels: 3
l2_lambda: 1.0
l1_lambda: 100
#use_annotation: True
use_fg_kp: False
num_tps: 10
kp_variance: 0.01
bg_label_index: 0
use_focal_loss: True
use_dice_loss: False
# focal loss params, ref suggests when incresing gamma, alpha should be reduced.
focal_alpha: 0.5
focal_gamma: 2.0
#out_channels: 64 #total 64 action-actor classes in A2D dataset
features: [64, 128, 256, 512]
bilinear: True
#Settings
learning_rate: 0.0001
monitor: 'val_loss'
epochs: 100
batch_size: 1
clear_cache: False
limit:
logger_dir: 'lightning_logs'
resume_ckpt: True
pspnet: 'resnet50'

