model_name: 'prnews_tte_sent'
skip_prep_data: True
neg_sample_ratio: 1.0
train_data_path: "data_model/prnews_tte_collab_filter_training.csv"
val_data_path: "data_model/prnews_tte_collab_filter_validation.csv"
train_val_split_ratio: [0.98, 0.02]
item_vocab_path: "data_model/prnews_item_vocab.json"
eval_data_path: ""
clear_cache: True
resume_ckpt: True

# CF model parameters
skip_training: True
monitor: "val_loss"
score_col: "scores"
query_col: "Text"
ref_col: "Company"
embed_size: 256
max_query_length: 512
logger_dir: "lightning_logs"
learning_rate: 0.0001
batch_size: 256
epochs: 50
limit:

analytics_examples:
  fpath: 'evaluators/prnews/analytics.csv'
  text_col: 'example_sent:analytics'
  ref_col: "company"
  sep: ','

innovation_examples:
  fpath: 'evaluators/prnews/innovation.csv'
  text_col: 'example_sent:innovation'
  ref_col: "company"
  sep: ','

technology_examples:
  fpath: 'evaluators/prnews/technology.csv'
  text_col: 'example_sent:technology'
  ref_col: "company"
  sep: ','