model_name: 'vit_sparse_coding'
encoder_type: "vit"
pretrained_model_name: "google/vit-base-patch16-224-in21k"
cubelet_size: [16, 16, 1]
clip_len: 32
frame_sample_rate: 1
omp_eps: 0.001
iter_max: 3000
#verbose: True
shuffle: True
eval_hmdb51:
  path: "C:/Users/shud0/Desktop/accountingInfoRetrieval-main/smartwebtext/data_model/video_recognition_hmdb51_test.csv"
  output_fpath: "evaluation/hmdb51_blended_cam/%s/{vid}.mp4"
  num_classes: 51
