model_name: 'vivit_sparse_coding'
encoder_type: "vivit"
pretrained_model_name: "google/vivit-b-16x2-kinetics400"
cubelet_size: [16, 16, 2]
clip_len: 32
frame_sample_rate: 1
omp_eps: 0.001
iter_max: 3000
shuffle: True
eval_hmdb51:
  path: "C:/Users/shud0/Desktop/accountingInfoRetrieval-main/smartwebtext/data_model/video_recognition_hmdb51_test.csv"
  output_fpath: "evaluation/hmdb51_blended_cam/%s/{vid}.mp4"
  num_classes: 51
